In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import sklearn.model_selection as cv
import sklearn
import warnings; warnings.simplefilter('ignore')

# Import data and transform to numerical value

In [2]:
## Load dataset
data = pd.read_csv("dataWithTextWordsPrep.csv", encoding='latin1', low_memory=False)
data.head()

Unnamed: 0   _unit_id  _golden _unit_state  _trusted_judgments  \
0           0  815719226    False   finalized                   3   
1           1  815719227    False   finalized                   3   
2           2  815719228    False   finalized                   3   
3           3  815719229    False   finalized                   3   
4           4  815719230    False   finalized                   3   

  _last_judgment_at  gender  gender:confidence profile_yn  \
0    10/26/15 23:24    male             1.0000        yes   
1    10/26/15 23:30    male             1.0000        yes   
2    10/26/15 23:33    male             0.6625        yes   
3    10/26/15 23:10    male             1.0000        yes   
4     10/27/15 1:15  female             1.0000        yes   

   profile_yn:confidence   ...    evidence great.  toe favor soccer did.  \
0                    1.0   ...           0      0    0     0      0    0   
1                    1.0   ...           0      0    0     0      0    0   
2                    1.0   ...           0      0    0     0      0    0   
3                    1.0   ...           0      0    0     0      0    0   
4                    1.0   ...           0      0    0     0      0    0   

  wheel shoulder  rank expected  
0     0        0     0        0  
1     0        0     0        0  
2     0        0     0        0  
3     0        0     0        0  
4     0        0     0        0  

[5 rows x 2027 columns]

In [3]:
data = data.drop(['Unnamed: 0', '_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at',
               'gender:confidence', 'profile_yn', 'profile_yn:confidence', 'created', 'description',
               'fav_number', 'gender_gold', 'link_color', 'name', 'profile_yn_gold', 'profileimage',
               'sidebar_color', 'text', 'tweet_count', 'tweet_created', 'tweet_id', 'tweet_location',
               'retweet_count', 'tweet_coord', 'user_timezone'], axis=1);
data = data[data.gender.notnull()]
data.head()

gender  you  weather  get  my  from  me  with  that  update    ...     \
0    male    0        0    0   0     0   0     0     0       0    ...      
1    male    0        0    0   1     0   0     1     0       0    ...      
2    male    0        0    0   0     0   1     0     0       0    ...      
3    male    1        0    0   0     0   0     0     0       0    ...      
4  female    0        0    0   0     0   0     1     0       0    ...      

   evidence  great.  toe  favor  soccer  did.  wheel  shoulder  rank  expected  
0         0       0    0      0       0     0      0         0     0         0  
1         0       0    0      0       0     0      0         0     0         0  
2         0       0    0      0       0     0      0         0     0         0  
3         0       0    0      0       0     0      0         0     0         0  
4         0       0    0      0       0     0      0         0     0         0  

[5 rows x 2001 columns]

In [4]:
# All values must be numeric, label included
def genderToNumeric(gender) :
    if gender == 'male' :
        return 0
    elif gender == 'female' :
        return 1
    else :
        return 2


labels = data.gender.apply(lambda g: genderToNumeric(g))
datadt = data.drop('gender', axis=1)

print(data.shape)
datadt.head()

(18836, 2001)


you  weather  get  my  from  me  with  that  update  be    ...     \
0    0        0    0   0     0   0     0     0       0   0    ...      
1    0        0    0   1     0   0     1     0       0   0    ...      
2    0        0    0   0     0   1     0     0       0   0    ...      
3    1        0    0   0     0   0     0     0       0   0    ...      
4    0        0    0   0     0   0     1     0       0   0    ...      

   evidence  great.  toe  favor  soccer  did.  wheel  shoulder  rank  expected  
0         0       0    0      0       0     0      0         0     0         0  
1         0       0    0      0       0     0      0         0     0         0  
2         0       0    0      0       0     0      0         0     0         0  
3         0       0    0      0       0     0      0         0     0         0  
4         0       0    0      0       0     0      0         0     0         0  

[5 rows x 2000 columns]

In [7]:
# Cross-validation: split data into training and test sets (test 30% of data)
data_train, data_test, labels_train, labels_test = cv.train_test_split(datadt, labels, test_size=.3, random_state=1)

In [8]:
data_train.info()
data.iloc[data_train.head().index]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13185 entries, 17267 to 235
Columns: 2000 entries, you to expected
dtypes: int64(2000)
memory usage: 201.3 MB


gender  you  weather  get  my  from  me  with  that  update    ...     \
17267   brand    0        0    0   0     0   0     0     0       0    ...      
14303    male    0        0    0   1     0   0     0     0       0    ...      
11018  female    0        0    0   0     0   0     0     0       0    ...      
9068     male    1        0    0   0     0   0     0     0       0    ...      
8696   female    0        0    0   0     0   0     0     0       0    ...      

       evidence  great.  toe  favor  soccer  did.  wheel  shoulder  rank  \
17267         0       0    0      0       0     0      0         0     0   
14303         0       0    0      0       0     0      0         0     0   
11018         0       0    0      0       0     0      0         0     0   
9068          0       0    0      0       0     0      0         0     0   
8696          0       0    0      0       0     0      0         0     0   

       expected  
17267         0  
14303         0  
11018         0  
9068          0  
8696          0  

[5 rows x 2001 columns]

In [9]:
data_test.info()
data.iloc[data_test.head().index]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5651 entries, 11871 to 18258
Columns: 2000 entries, you to expected
dtypes: int64(2000)
memory usage: 86.3 MB


gender  you  weather  get  my  from  me  with  that  update    ...     \
11871  female    0        0    0   0     0   0     0     0       0    ...      
7136    brand    0        1    1   0     1   0     0     0       1    ...      
13818    male    0        0    0   0     0   0     0     0       0    ...      
5231    brand    0        0    0   0     0   0     0     0       0    ...      
1005    brand    0        0    0   0     0   0     0     0       0    ...      

       evidence  great.  toe  favor  soccer  did.  wheel  shoulder  rank  \
11871         0       0    0      0       0     0      0         0     0   
7136          0       0    0      0       0     0      0         0     0   
13818         0       0    0      0       0     0      0         0     0   
5231          0       0    0      0       0     0      0         0     0   
1005          0       0    0      0       0     0      0         0     0   

       expected  
11871         0  
7136          0  
13818         0  
5231          0  
1005          0  

[5 rows x 2001 columns]

# DT without parameters optimization

In [10]:
from sklearn import tree
from sklearn.externals.six import StringIO  
import pydot
from IPython.display import Image 
from statsmodels.stats.proportion import proportion_confint

clf = tree.DecisionTreeClassifier(criterion='entropy')
pred = clf.fit(data_train, labels_train).predict(data_test)
print(sklearn.metrics.confusion_matrix(labels_test, pred))
print()
print("Accuracy on test set:", sklearn.metrics.accuracy_score(labels_test, pred))
print()
print(sklearn.metrics.classification_report(labels_test, pred))
epsilon = sklearn.metrics.accuracy_score(labels_test, pred)
print("Confidence interval: ",proportion_confint(count=epsilon*data_test.shape[0], nobs=data_test.shape[0], alpha=0.05, method='binom_test'))

[[758 695 362]
 [718 995 318]
 [452 450 903]]

Accuracy on test set: 0.470005308795

             precision    recall  f1-score   support

          0       0.39      0.42      0.41      1815
          1       0.46      0.49      0.48      2031
          2       0.57      0.50      0.53      1805

avg / total       0.48      0.47      0.47      5651

Confidence interval:  (0.4569965992324414, 0.4830994587074703)


# Search DT best parameters

In [11]:
from sklearn.model_selection import GridSearchCV
params = {'min_impurity_split': list(np.linspace(0,1,21)),'min_samples_split':list(range(2,102,11))}
clf = (tree.DecisionTreeClassifier(criterion='entropy'), param_grid=params,cv=10,n_jobs=-1)  # If cv is integer, by default is Stratifyed 
clf.fit(data_train, labels_train)
print("Best Params=",clf.best_params_, "Accuracy=", clf.best_score_)

Best Params= {'min_impurity_split': 1.0, 'min_samples_split': 79} Accuracy= 0.465073947668


# K-Fold-Cross-Validation

In [12]:
from sklearn import tree
from sklearn.externals.six import StringIO  
import pydot
from IPython.display import Image 
from statsmodels.stats.proportion import proportion_confint
import sklearn.cross_validation as cv

sum_accuracy = 0
sum_conf_interval = [0, 0]

kf = cv.KFold(len(datadt), n_folds=10)

for train_index, test_index in kf :

    data_train, data_test = pd.core.frame.DataFrame(datadt, index = train_index), pd.core.frame.DataFrame(datadt ,index = test_index)
    labels_train, labels_test = pd.core.frame.DataFrame(labels, index = train_index), pd.core.frame.DataFrame(labels ,index = test_index)
    
    clf = tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=79, min_impurity_split=1.0)
    pred = clf.fit(data_train, labels_train).predict(data_test)
    
    epsilon = sklearn.metrics.accuracy_score(labels_test, pred)
    conf_interval = proportion_confint(count=epsilon*data_test.shape[0], nobs=data_test.shape[0], alpha=0.05, method='binom_test')  
    
    sum_accuracy += sklearn.metrics.accuracy_score(labels_test, pred)
    sum_conf_interval[0] += conf_interval[0]
    sum_conf_interval[1] += conf_interval[1]
    
    
print("Accuracy on test set:", sum_accuracy/kf.n_folds)
print()
print(f'Confidence interval: ({sum_conf_interval[0]/kf.n_folds}, {sum_conf_interval[1]/kf.n_folds})')



Accuracy on test set: 0.464318863719

Confidence interval: (0.4419058342247431, 0.4868269693010361)
